drop database QUANLIPHUOT
CREATE DATABASE QUANLIPHUOT
ON ( NAME = 'QUANLIPHUOT_dat', 
FILENAME = 'E:\DATA\Database\QUANLIPHUOT\QUANLIPHUOT.mdf', 
SIZE = 10, MAXSIZE = 50, FILEGROWTH = 5 ) 
LOG ON ( NAME = 'QUANLIPHUOT_log', 
FILENAME = 'E:\DATA\Database\QUANLIPHUOT\QUANLIPHUOT_log.ldf', 
SIZE = 5MB, MAXSIZE = 25MB, FILEGROWTH = 5MB ) 
USE QUANLIPHUOT
CREATE FUNCTION AUTO_IDNV()
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA_NV) FROM NHANVIEN) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA_NV, 3)) FROM NHANVIEN
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NV00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NV0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
CREATE FUNCTION AUTO_IDHD()
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA_HD) FROM HOADON) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA_HD, 3)) FROM HOADON
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'HD00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'HD0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
CREATE FUNCTION AUTO_IDNSX()
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ID VARCHAR(6)
	IF (SELECT COUNT(MA_NSX) FROM NHASANXUAT) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA_NSX, 2)) FROM NHASANXUAT
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'NSX00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'NSX0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

CREATE FUNCTION AUTO_IDKH()
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA_KH) FROM KHACHHANG) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA_KH, 3)) FROM KHACHHANG
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'KH00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'KH0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END

CREATE FUNCTION AUTO_IDSP()
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA_SP) FROM SANPHAM) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA_SP, 3)) FROM SANPHAM
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'SP00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'SP0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
CREATE FUNCTION AUTO_IDPN()
RETURNS VARCHAR(20)
AS
BEGIN
	DECLARE @ID VARCHAR(5)
	IF (SELECT COUNT(MA_PN) FROM PHIEUNHAP) = 0
		SET @ID = '0'
	ELSE
		SELECT @ID = MAX(RIGHT(MA_PN, 3)) FROM PHIEUNHAP
		SELECT @ID = CASE
			WHEN @ID >= 0 and @ID < 9 THEN 'PN00' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
			WHEN @ID >= 9 THEN 'PN0' + CONVERT(CHAR, CONVERT(INT, @ID) + 1)
		END
	RETURN @ID
END
CREATE TABLE KHACHHANG
(
	MA_KH VARCHAR(20) PRIMARY KEY CONSTRAINT IDKH DEFAULT DBO.AUTO_IDKH(),
	HOTEN_KH NVARCHAR(100),
	SDT_KH VARCHAR(15),
	DIACHI_KH NVARCHAR(100)
)
INSERT INTO KHACHHANG(HOTEN_KH,SDT_KH,DIACHI_KH) VALUES('THIEN','123123123','TP.HCM')
CREATE TABLE NHASANXUAT
(
	MA_NSX VARCHAR(20) PRIMARY KEY CONSTRAINT IDNSX DEFAULT DBO.AUTO_IDNSX(),
	TEN_NSX NVARCHAR(50),
	DT_NSX VARCHAR(20),
	DIACHI_NSX NVARCHAR(100)
)
INSERT INTO NHASANXUAT(TEN_NSX,DT_NSX,DIACHI_NSX) VALUES('ADIDAS','434853545','USA')

CREATE TABLE NHANVIEN
(
	MA_NV VARCHAR(20) PRIMARY KEY CONSTRAINT IDNV DEFAULT DBO.AUTO_IDNV(),
	TEN_NV NVARCHAR(50),
	NS_NV DATETIME,
	GT_NV NVARCHAR(5),
	DT_NV VARCHAR(20),
	NGAYVAOLAM_NV DATETIME,
	DIACHI_NV NVARCHAR(100)
)
INSERT INTO NHANVIEN(TEN_NV,NS_NV,GT_NV,DT_NV,NGAYVAOLAM_NV,DIACHI_NV) VALUES('THIEN','12/12/1990','NAM','0123123','12/12/2012',N'QUAN 11')
ALTER TABLE NHANVIEN
	ADD CONSTRAINT NGAYVAOLAM_NV CHECK((YEAR(NGAYVAOLAM_NV)-YEAR(NS_NV))>=18);
CREATE TABLE SANPHAM
(
	MA_SP VARCHAR(20) PRIMARY KEY CONSTRAINT IDSP DEFAULT DBO.AUTO_IDSP(),
	TEN_SP NVARCHAR(50),
	GIA_SP FLOAT,
	NGUYENLIEU_SP NVARCHAR(50),
	MA_NSX VARCHAR(20) FOREIGN KEY(MA_NSX) REFERENCES NHASANXUAT(MA_NSX),
)
INSERT INTO SANPHAM(TEN_SP,GIA_SP,NGUYENLIEU_SP,MA_NSX) VALUES('GIAY ADIDAS',120000,'DA',(SELECT MAX(MA_NSX) FROM NHASANXUAT))
CREATE TABLE HOADON
(
	MA_HD VARCHAR(20) PRIMARY KEY CONSTRAINT IDHD DEFAULT DBO.AUTO_IDHD(),
	NGAYLAP_HD DATETIME,
	MA_KH VARCHAR(20) FOREIGN KEY(MA_KH) REFERENCES KHACHHANG(MA_KH),
	MA_NV VARCHAR(20) FOREIGN KEY(MA_NV) REFERENCES NHANVIEN(MA_NV),
	TONGTIEN FLOAT
)
INSERT INTO HOADON(NGAYLAP_HD,MA_KH,MA_NV) VALUES('12/12/2015','KH001','NV001')
SELECT * FROM HOADON
CREATE TABLE CTHOADON
(
	MA_HD VARCHAR(20) FOREIGN KEY (MA_HD) REFERENCES HOADON(MA_HD),
	MA_SP VARCHAR(20) FOREIGN KEY (MA_SP) REFERENCES SANPHAM(MA_SP),
	PRIMARY KEY (MA_HD,MA_SP),
	SL TINYINT,
	DVT NVARCHAR(10),
	THANHTIEN FLOAT,
)
INSERT INTO CTHOADON(MA_HD,MA_SP,SL,DVT,THANHTIEN) VALUES((SELECT MAX(MA_HD) FROM HOADON),'SP001',11,'DOI',12000)

SELECT *  FROM HOADON 
SELECT *  FROM CTHOADON 

SELECT A.MA_HD,NGAYLAP_HD,A.MA_KH,HOTEN_KH,A.MA_NV, TEN_NV,B.MA_SP,TEN_SP,SL,DVT,THANHTIEN
FROM HOADON A, CTHOADON B,SANPHAM C,KHACHHANG D,NHANVIEN E
WHERE A.MA_HD=B.MA_HD AND A.MA_NV=E.MA_NV AND B.MA_SP=C.MA_SP AND A.MA_KH=D.MA_KH
CREATE TABLE PHIEUNHAP
(
	MA_PN VARCHAR(20) PRIMARY KEY CONSTRAINT IDPN DEFAULT DBO.AUTO_IDPN(),
	NGAYNHAP DATETIME,
	MA_NV VARCHAR(20) FOREIGN KEY(MA_NV) REFERENCES NHANVIEN(MA_NV)
)
CREATE TABLE CTPHIEUNHAP
(
	MA_SP VARCHAR(20) FOREIGN KEY(MA_SP) REFERENCES SANPHAM(MA_SP),
	MA_PN VARCHAR(20) FOREIGN KEY(MA_PN) REFERENCES PHIEUNHAP(MA_PN),
	PRIMARY KEY(MA_PN,MA_SP),
	GIA_NHAP FLOAT,
	SOLUONG TINYINT,
)
CREATE TABLE NGUOIDUNG
(
	TK nvarchar(20) primary key,
	MK nvarchar(20)
)
select * from SANPHAM
update NHASANXUAT set TEN_NSX = N'Adidas',DT_NSX = '434853545',DIACHI_NSX=N'USA' where Ma_NV = 'NSX001'
delete from NHASANXUAT
select * from NHASANXUAT
update NHASANXUAT set XOA = 0
select * from KHACHHANG
delete from KHACHHAN
update SANPHAM set XOA = 0
insert into KHACHHANG(TEN_KH,DT_KH,DIACHI_KH) values(N'đĩ thọ','32232323',N'trần khắc chân')
update KHACHHANG set XOA = 0 where MA_KH = 'KH002'
select * from SANPHAM
delete from SANPHAM where 
select * from CTHOADON
delete from CTHOADON